language: r
r:
  - oldrel
  - release
  - devel
#sudo: required
warnings_are_errors: true
r_packages:
  - rgenoud
  - foreach
  - doParallel
  - testthat
  - numDeriv
os:
  - linux
  - osx
#before_install:
#- if [ "$TRAVIS_OS_NAME" = "osx" ] ; then sudo chown -R $(whoami) /usr/local ; brew update ; brew reinstall --force gcc48 --with-fortran; fi
r_github_packages:
  - r-lib/covr
after_success:
  - Rscript -e 'covr::codecov()'
