language: r
r:
  - oldrel
  - release
  - devel
branches:
  only:
    master
#sudo: required
warnings_are_errors: true
r_packages:
  - rgenoud
  - foreach
  - doParallel
  - testthat
  - numDeriv
  - covr
#cache: packages
os:
  - linux
  - osx
    
addons:
  apt:
    packages:
      - libssh2-1-dev
before_install:
  - brew install libgit2

after_success:
  - Rscript -e 'covr::codecov()'
  
before_deploy:
      - git tag "DiceKriging-latest"
deploy:
  provider: releases
  name: DiceKriging_latest-LinuxOSX
  api_key:
    secure: "GAD1xvd6MajE8AasywvMuDApe73z0wDBsRwZ/V1QQgf4oyrbM17P63HuHd3gxVEwKXP3TqTaYKHqlOnPWsgm//FqIkj0Ai6TBVrxCOWrSkN5yxyNV3A49JfwUtpN/7hPK4K8jR04jKU/XqSMA6Qm5q6ykp314BhNTPkhhjUNark="
  file_glob: true
  file: DiceKriging*.gz
  skip_cleanup: true
