language: r
r:
  - oldrel
  - release
  - devel
branches:
  only:
    master

warnings_are_errors: true
r_packages:
  - rgenoud
  - foreach
  - doParallel
  - testthat
  - numDeriv
  - covr
cache: packages

os:
  - linux
  - osx
    
addons:
  apt:
    packages:
      - libssh2-1-dev
      
before_install:
  - echo "$TRAVIS_OS_NAME"
  - echo "$TRAVIS_R_VERSION"
  - echo $PKG_TARBALL
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then sudo chown -R $(whoami) /usr/local ; brew install libgit2; fi
  
after_success:
  - if [[ "$TRAVIS_R_VERSION" == "release" && ("$TRAVIS_OS_NAME" == "linux") ]]; then Rscript -e 'covr::codecov()'; fi
  
before_deploy:
  - git tag "$(git log --date=iso  -1 | grep Date | sed -e 's/Date:\ *//' -e 's/\+.*//' -e 's/[- :]//g')-$(git log --format=%h --abbrev=8 -1)" || true
  - if [[ "$TRAVIS_R_VERSION" == "release" && ("$TRAVIS_OS_NAME" == "osx") ]]; then R CMD INSTALL --build $PKG_TARBALL; fi

deploy:
  provider: releases
  name: "DiceKriging-$TRAVIS_OS_NAME"
  api_key:
    secure: "GAD1xvd6MajE8AasywvMuDApe73z0wDBsRwZ/V1QQgf4oyrbM17P63HuHd3gxVEwKXP3TqTaYKHqlOnPWsgm//FqIkj0Ai6TBVrxCOWrSkN5yxyNV3A49JfwUtpN/7hPK4K8jR04jKU/XqSMA6Qm5q6ykp314BhNTPkhhjUNark="
  file_glob: true
  file: DiceKriging*.t*gz
  skip_cleanup: true
  overwrite: true
  on:
    r: release
