# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here
branches:
  only:
    - master
    
build_script:
  - travis-tool.sh install_deps
  - ps: $env:VERSION_RELEASE="$(date +%Y%m%d-%H%M)"
  - echo %VERSION_RELEASE%

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: log

  - path: '*.Rcheck\**\*.out'
    name: log

  - path: '*.Rcheck\**\*.fail'
    name: log

  - path: '*.Rcheck\**\*.Rout'
    name: log

  - path: '\*_*.tar.gz'
    name: src

  - path: '\*_*.zip'
    name: bin
    type: zip
    
before_deploy:
     - git tag %VERSION_RELEASE%
deploy:
  provider: GitHub
  release: windows
  auth_token:
    secure:  DAGNQm9WOY/5YmstALy9O3oJ8UE9b0BRjHZtcy977Tp1pOTv5soBrnK2B6DQVetL
  artifact: bin
  draft: false
  prerelease: false
  force_update: true
  on:
    branch:
      master
    except:
      - linux
      - osx

